- name: play for setting computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_architecture == 'x86_64' else
          'arm64' if ansible_architecture == 'aarch64' else
          ansible_architecture
          }}

- hosts: all
  become: true
  become_user: "{{ target_user }}"
  roles:
    - role: userconfig

- hosts: all
  become: true
  roles:
    - role: system
      timezone: Europe/Helsinki
      install_packages:
        - git
        - ansible
        - gpg
        - curl
        - net-tools
        - bind9-dnsutils
        - systemd-container

    - role: security
      ssh_service_name: "sshd"
