- name: set computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_architecture == 'x86_64' else
          'arm64' if ansible_architecture == 'aarch64' else
          ansible_architecture
          }}

- name: configure primary dns server
  hosts: all
  become: true
  roles:
    - role: docker

    - role: bind9
      bind9_timezone: Europe/Helsinki
      bind9_master: false
      bind9_slave: true
