- name: set computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_facts['architecture'] == 'x86_64' else
          'arm64' if ansible_facts['architecture'] == 'aarch64' else
          ansible_facts['architecture']
          }}

- name: configure edge server
  hosts: all
  become: true
  roles:
    - role: application
      application_name: "haproxy-edge"
      application_container_path: "{{ playbook_dir }}/apps/haproxy-edge/quadlet"
      application_config_path: "{{ playbook_dir }}/apps/haproxy-edge/config"
      application_quadlet_units:
        - haproxy-edge
