- name: set computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_architecture == 'x86_64' else
          'arm64' if ansible_architecture == 'aarch64' else
          ansible_architecture
          }}

- name: user level configurations
  hosts: all
  become: true
  become_user: "{{ sops_general.target_user }}"
  roles:
    - role: userconfig

- name: basic configuration for all debian systems
  hosts: all
  become: true
  roles:
    - role: ssh_keysign
      ssh_keysign_ssh_service_name: "sshd"
      ssh_keysign_version: "0.0.7"
      ssh_keysign_checksum: "sha256:c2217d2edd0be91c9ccd335908d032cd804576f43dffd9984e507c0db4a6d08a"
      ssh_keysign_certificate: true
