- name: pre-requisite packages for secret management
  hosts: all
  become: true
  roles:
    - role: sops
      sops_version: "3.11.0"
      sops_deb_url: "https://github.com/getsops/sops/releases/download/v{{ sops_version }}/sops_{{ sops_version }}_amd64.deb"
      sops_checksum_sha256: "0cba49ca030a77a86105104b54bfc5579d1edf4983e0efa43d046d8b9b95dd82"
      sops_download_path: "/tmp/sops_{{ sops_version }}_amd64.deb"

- name: basic configuration for all debian systems
  hosts: all
  become: true
  roles:
    - role: system
      system_allow_release_info_change: false
      system_timezone: "Europe/Helsinki"
      system_install_packages:
        - age
        - ansible-core
        - bind9-dnsutils
        - curl
        - git
        - gpg
        - net-tools
        - qemu-guest-agent
        - systemd-container

    - role: security
      security_ssh_service_name: "sshd"

    - role: ssh_keysign
      ssh_keysign_ssh_service_name: "sshd"
      ssh_keysign_version: "0.0.7"
      ssh_keysign_checksum: "sha256:c2217d2edd0be91c9ccd335908d032cd804576f43dffd9984e507c0db4a6d08a"
      ssh_keysign_certificate: false

    - role: docker
    - role: cloudyhome
