collections:
  - name: community.general
    version: "12.0.1"
  - name: community.docker
    version: "5.0.1"
  - name: ansible.posix
    version: "2.1.0"
  - name: kpfleming.powerdns_auth
    version: "25.2.0"
  - name: community.sops
    version: "2.2.7"
