- name: set computed facts
  hosts: all
  tasks:
    - name: set normalized architecture fact
      ansible.builtin.set_fact:
        normalized_arch: >-
          {{
          'amd64' if ansible_architecture == 'x86_64' else
          'arm64' if ansible_architecture == 'aarch64' else
          ansible_architecture
          }}

- name: configure primary dns server
  hosts: all
  become: true
  roles:
    - role: docker
    - role: github_runner
      github_runner_url: "{{ sops_gh.gh_runner_url }}"
      github_runner_token: "{{ sops_gh.gh_runner_token }}"
      github_runner_app_id: "{{ sops_gh.gh_runner_app_id }}"
      github_runner_client_id: "{{ sops_gh.gh_runner_client_id }}"
      github_runner_installation_id: "{{ sops_gh.gh_runner_installation_id }}"
      github_runner_private_key: "{{ sops_gh.gh_runner_private_key }}"
