name: ansible-lint

on:
  push:
    branches: ['*']

jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          requirements_file: "requirements.yml"
